version: "3"
services:
    php:
        container_name: php
        ports:
            - 4000:80
            - 5133:5133
        volumes:
            - ./:/var/www
        image: vigilio/php:0.0.4

        depends_on:
            - db
        networks:
            default:
                aliases:
                    - vite-php-setup.test
            vite-php-setup:

    db:
        image: mysql:8.0.2
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysqlpe
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=dokixd123
            - MYSQL_PASSWORD=doki
            - MYSQL_DATABASE=db
        volumes:
            - mysqldb:/var/lib/mysql
            - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
        restart: always

volumes:
    mysqldb:
networks:
    vite-php-setup:
