version: "3.7"
services:
    app:
        build: ./docker
        container_name: php
        image: vigilio/php-mvc:0.0.4
        ports:
            - "4000:80"
            - "5133:5133"
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            default:
                aliases:
                    - vite-php-setup.test
            vite-php-setup:
    db:
        image: mysql:8.0.2
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    mysql-data:
networks:
    vite-php-setup:
